# Generated by Django 3.2.11 on 2022-01-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0053_alter_customer_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
