# Generated by Django 3.2.11 on 2022-01-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0056_rename_enroll_teacher_student_enroll_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
