# Generated by Django 3.2.11 on 2022-01-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0057_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
    ]
